# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhangzhao/SCD-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhangzhao/SCD-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangzhao/SCD-master/CMakeFiles /home/zhangzhao/SCD-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangzhao/SCD-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scd

# Build rule for target.
scd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scd
.PHONY : scd

# fast build rule for target.
scd/fast:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/build
.PHONY : scd/fast

#=============================================================================
# Target rules for targets named wcc

# Build rule for target.
wcc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wcc
.PHONY : wcc

# fast build rule for target.
wcc/fast:
	$(MAKE) -f tools/wcc/CMakeFiles/wcc.dir/build.make tools/wcc/CMakeFiles/wcc.dir/build
.PHONY : wcc/fast

#=============================================================================
# Target rules for targets named f1score

# Build rule for target.
f1score: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 f1score
.PHONY : f1score

# fast build rule for target.
f1score/fast:
	$(MAKE) -f tools/f1score/CMakeFiles/f1score.dir/build.make tools/f1score/CMakeFiles/f1score.dir/build
.PHONY : f1score/fast

source/common/time.o: source/common/time.cpp.o
.PHONY : source/common/time.o

# target to build an object file
source/common/time.cpp.o:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/common/time.cpp.o
.PHONY : source/common/time.cpp.o

source/common/time.i: source/common/time.cpp.i
.PHONY : source/common/time.i

# target to preprocess a source file
source/common/time.cpp.i:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/common/time.cpp.i
.PHONY : source/common/time.cpp.i

source/common/time.s: source/common/time.cpp.s
.PHONY : source/common/time.s

# target to generate assembly for a file
source/common/time.cpp.s:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/common/time.cpp.s
.PHONY : source/common/time.cpp.s

source/communities/communities.o: source/communities/communities.cpp.o
.PHONY : source/communities/communities.o

# target to build an object file
source/communities/communities.cpp.o:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/communities/communities.cpp.o
.PHONY : source/communities/communities.cpp.o

source/communities/communities.i: source/communities/communities.cpp.i
.PHONY : source/communities/communities.i

# target to preprocess a source file
source/communities/communities.cpp.i:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/communities/communities.cpp.i
.PHONY : source/communities/communities.cpp.i

source/communities/communities.s: source/communities/communities.cpp.s
.PHONY : source/communities/communities.s

# target to generate assembly for a file
source/communities/communities.cpp.s:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/communities/communities.cpp.s
.PHONY : source/communities/communities.cpp.s

source/graph/graph.o: source/graph/graph.cpp.o
.PHONY : source/graph/graph.o

# target to build an object file
source/graph/graph.cpp.o:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/graph/graph.cpp.o
.PHONY : source/graph/graph.cpp.o

source/graph/graph.i: source/graph/graph.cpp.i
.PHONY : source/graph/graph.i

# target to preprocess a source file
source/graph/graph.cpp.i:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/graph/graph.cpp.i
.PHONY : source/graph/graph.cpp.i

source/graph/graph.s: source/graph/graph.cpp.s
.PHONY : source/graph/graph.s

# target to generate assembly for a file
source/graph/graph.cpp.s:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/graph/graph.cpp.s
.PHONY : source/graph/graph.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/wcc/wcc.o: source/wcc/wcc.cpp.o
.PHONY : source/wcc/wcc.o

# target to build an object file
source/wcc/wcc.cpp.o:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/wcc/wcc.cpp.o
.PHONY : source/wcc/wcc.cpp.o

source/wcc/wcc.i: source/wcc/wcc.cpp.i
.PHONY : source/wcc/wcc.i

# target to preprocess a source file
source/wcc/wcc.cpp.i:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/wcc/wcc.cpp.i
.PHONY : source/wcc/wcc.cpp.i

source/wcc/wcc.s: source/wcc/wcc.cpp.s
.PHONY : source/wcc/wcc.s

# target to generate assembly for a file
source/wcc/wcc.cpp.s:
	$(MAKE) -f CMakeFiles/scd.dir/build.make CMakeFiles/scd.dir/source/wcc/wcc.cpp.s
.PHONY : source/wcc/wcc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... scd"
	@echo "... wcc"
	@echo "... f1score"
	@echo "... source/common/time.o"
	@echo "... source/common/time.i"
	@echo "... source/common/time.s"
	@echo "... source/communities/communities.o"
	@echo "... source/communities/communities.i"
	@echo "... source/communities/communities.s"
	@echo "... source/graph/graph.o"
	@echo "... source/graph/graph.i"
	@echo "... source/graph/graph.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/wcc/wcc.o"
	@echo "... source/wcc/wcc.i"
	@echo "... source/wcc/wcc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

